export enum RCIncomingPacket {
	PLO_DISCMESSAGE				= 16,
	PLO_SIGNATURE				= 25,
	PLO_FILESENDFAILED			= 30,
	PLO_NEWWORLDTIME			= 42,
	PLO_RC_ACCOUNTADD			= 50,	// Deprecated.  Codr note: Unhandled by 6.037.
	PLO_RC_ACCOUNTSTATUS		= 51,	// Deprecated.  Codr note: Unhandled by 6.037.
	PLO_RC_ACCOUNTNAME			= 52,	// Deprecated.  Codr note: Unhandled by 6.037.
	PLO_RC_ACCOUNTDEL			= 53,	// Deprecated.  Codr note: Unhandled by 6.037.
	PLO_RC_ACCOUNTPROPS			= 54,	// Deprecated.  Codr note: Unhandled by 6.037.
	PLO_ADDPLAYER				= 55,	// Unhandled by 5.07+. -Codr
	PLO_DELPLAYER				= 56,
	PLO_RC_ACCOUNTPROPSGET		= 57,	// Deprecated.  Codr note: Unhandled by 6.037.
	PLO_RC_ACCOUNTCHANGE		= 58,	// Deprecated.  Codr note: Unhandled by 6.037.
	PLO_RC_PLAYERPROPSCHANGE	= 59,	// Deprecated.  Codr note: Unhandled by 6.037.
	PLO_UNKNOWN60				= 60,	// Unhandled by 5.07+. -Codr
	PLO_RC_SERVERFLAGSGET		= 61,	// Unhandled by 5.07+. -Codr
	PLO_RC_PLAYERRIGHTSGET		= 62,	// Unhandled by 5.07+. -Codr
	PLO_RC_PLAYERCOMMENTSGET	= 63,	// Unhandled by 5.07+. -Codr
	PLO_RC_PLAYERBANGET			= 64,	// Unhandled by 5.07+. -Codr
	PLO_RC_FILEBROWSER_DIRLIST	= 65,	// Unhandled by 5.07+. -Codr
	PLO_RC_FILEBROWSER_DIR		= 66,	// Unhandled by 5.07+. -Codr
	PLO_RC_FILEBROWSER_MESSAGE	= 67,
	PLO_LARGEFILESTART			= 68,
	PLO_LARGEFILEEND			= 69,
	PLO_RC_ACCOUNTLISTGET		= 70,	// Unhandled by 5.07+. -Codr
	PLO_RC_PLAYERPROPS			= 71,	// Deprecated.  Codr note: Unhandled by 6.037.
	PLO_RC_PLAYERPROPSGET		= 72,	// Unhandled by 5.07+. -Codr
	PLO_RC_ACCOUNTGET 			= 73,
	PLO_RCCHAT 					= 74,
	PLO_RC_SERVEROPTIONSGET 	= 76,
	PLO_RC_FOLDERCONFIGGET 		= 77,
	PLO_NPCSERVERADDR 			= 79,
	PLO_LARGEFILESIZE			= 84,
	PLO_RAWDATA 				= 100,
	PLO_FILE 					= 102,
	PLO_RC_MAXUPLOADFILESIZE 	= 103,
}

export enum RCOutgoingPacket {
	PLI_PLAYERPROPS 			= 2,
	PLI_RC_SERVEROPTIONSGET 	= 51,
	PLI_RC_SERVEROPTIONSSET 	= 52,
	PLI_RC_FOLDERCONFIGGET 		= 53,
	PLI_RC_FOLDERCONFIGSET 		= 54,
	PLI_RC_RESPAWNSET 			= 55,
	PLI_RC_HORSELIFESET 		= 56,
	PLI_RC_APINCREMENTSET 		= 57,
	PLI_RC_BADDYRESPAWNSET 		= 58,
	PLI_RC_PLAYERPROPSGET 		= 59,
	PLI_RC_PLAYERPROPSSET 		= 60,
	PLI_RC_DISCONNECTPLAYER 	= 61,
	PLI_RC_UPDATELEVELS 		= 62,
	PLI_RC_ADMINMESSAGE 		= 63,
	PLI_RC_PRIVADMINMESSAGE 	= 64,
	PLI_RC_LISTRCS = 65,
	PLI_RC_DISCONNECTRC = 66,
	PLI_RC_APPLYREASON = 67,
	PLI_RC_SERVERFLAGSGET = 68,
	PLI_RC_SERVERFLAGSSET = 69,
	PLI_RC_ACCOUNTADD = 70,
	PLI_RC_ACCOUNTDEL = 71,
	PLI_RC_ACCOUNTLISTGET = 72,
	PLI_RC_PLAYERPROPSGET2 = 73,
	PLI_RC_PLAYERPROPSGET3 = 74,
	PLI_RC_PLAYERPROPSRESET = 75,
	PLI_RC_PLAYERPROPSSET2 = 76,
	PLI_RC_ACCOUNTGET = 77,
	PLI_RC_ACCOUNTSET = 78,
	PLI_RCCHAT = 79,
	PLI_RC_WARPPLAYER = 82,
	PLI_RC_PLAYERRIGHTSGET = 83,
	PLI_RC_PLAYERRIGHTSSET = 84,
	PLI_RC_PLAYERCOMMENTSGET = 85,
	PLI_RC_PLAYERCOMMENTSSET = 86,
	PLI_RC_PLAYERBANGET = 87,
	PLI_RC_PLAYERBANSET = 88,
	PLI_RC_FILEBROWSER_START = 89,
	PLI_RC_FILEBROWSER_CD = 90,
	PLI_RC_FILEBROWSER_END = 91,
	PLI_RC_FILEBROWSER_DOWN = 92,
	PLI_RC_FILEBROWSER_UP = 93,
	PLI_NPCSERVERQUERY = 94,
	PLI_RC_FILEBROWSER_MOVE = 96,
	PLI_RC_FILEBROWSER_DELETE = 97,
	PLI_RC_FILEBROWSER_RENAME = 98,
	PLI_RC_LARGEFILESTART = 155,
	PLI_RC_LARGEFILEEND = 156,
	PLI_RC_FOLDERDELETE = 160,
	PLI_RC_UNKNOWN162 = 162
}

export enum NCIncomingPacket {
	PLO_NEWWORLDTIME = 42,
	PLO_RCCHAT = 74,
	PLO_NC_CONTROL = 78,
	PLO_NC_LEVELLIST = 80,
	PLO_NC_NPCATTRIBUTES = 157,
	PLO_NC_NPCADD = 158,
	PLO_NC_NPCDELETE = 159,
	PLO_NC_NPCSCRIPT = 160,
	PLO_NC_NPCFLAGS = 161,
	PLO_NC_CLASSGET = 162,
	PLO_NC_CLASSADD = 163,
	PLO_NC_LEVELDUMP = 164,
	PLO_NC_WEAPONLISTGET = 167,
	PLO_NC_CLASSDELETE = 188,
	PLO_NC_WEAPONGET = 192
}

export enum NCOutgoingPacket {
	PLI_NC_NPCGET = 103,
	PLI_NC_NPCDELETE = 104,
	PLI_NC_NPCRESET = 105,
	PLI_NC_NPCSCRIPTGET = 106,
	PLI_NC_NPCWARP = 107,
	PLI_NC_NPCFLAGSGET = 108,
	PLI_NC_NPCSCRIPTSET = 109,
	PLI_NC_NPCFLAGSSET = 110,
	PLI_NC_NPCADD = 111,
	PLI_NC_CLASSEDIT = 112,
	PLI_NC_CLASSADD = 113,
	PLI_NC_LOCALNPCSGET = 114,
	PLI_NC_WEAPONLISTGET = 115,
	PLI_NC_WEAPONGET = 116,
	PLI_NC_WEAPONADD = 117,
	PLI_NC_WEAPONDELETE = 118,
	PLI_NC_CLASSDELETE = 119,
	PLI_NC_LEVELLISTGET = 150,
	PLI_NC_LEVELLISTSET = 151,
}

export enum PlayerProperties {
	PLPROP_NICKNAME = 0,
	PLPROP_ID = 14,
	PLPROP_ADDITFLAGS = 33,
	PLPROP_PSTATUSMSG = 53
}